openapi: 3.0.3
info:
  title: Default value on reference
  version: '1.0.1'
paths:
  /test1:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    $ref: '#/components/schemas/MyObject'
                    default:
                      prop1: Test 1
                      prop2: Test 2
components:
  schemas:
    MyObject:
      type: object
      description: MyObject description
      properties:
        prop1:
          type: string
          description: Prop1 description
        prop2:
          type: string
