openapi: 3.0.1
info:
  title: Example
  version: '1.0'
paths:
  /test:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './external-nested-ref-part.yml#/components/schemas/Y'
